debug:
    matmul_precision: "high"  # "highest", "high", "medium"

# Train Hyperparameters
train:
    n_epochs: 10  # 30 ok
    lr: 0.0001
    wd: 0.0001
    num_workers: 6  # optimal 6
    batch_size: 16  # optimal 32
    pin_memory: True
    persistent_workers: True
    prefetch_factor: 4  # optimal 4
    resume_training_model: "empty"

test:
    model_name: "model50_dbmel_student.pt"
    batch_size: 32
    mu: 0.05 # Label Smoothing 
    topN: 1

# Data Augmentation and sampling Config
augment:
    gamma: -0.5
    p_noise: 0.0  #0.50
    alpha: 0.0    #0.3 
    p_soundscape_noise: 0.0   #0.50 # p to chose noise from soundscapes instead of esc50
    p_mix: 0.0    #0.55
    p_filter: 0.0 #0.25
    p_mask: 0.0   #0.50
    
    
# Model Config
model:
    dropout: 0.25
    m_type: "dbmel"   #"dbmel" , "wigner"

# Spectrogram Config
spectrogram: 
    n_fft: 2048
    hop_length: 512
    n_mels: 128

# Configs of spectrogram
#Wigner: 
   #n_fft: 1024
    #hop_length: 1024
    #n_mels: 128
#ballanced 
    #n_fft: 2048
    #hop_length: 512
    #n_mels: 128
# better temporal resolution (aves)
    #n_fft: 2048
    #hop_length: 512
    #n_mels: 256
#better frequency resolution (short calls)
    #n_fft: 1024
    #hop_length: 320
    #n_mels: 128


# Combined Loss (BCE + Focal) # final_loss = 0.3 * BCE + 0.7 * Focal
loss:
    beta: 0.5 #
    rho: 2.0



